name: python-lint

on:
  workflow_call:

jobs:
  flake8-lint:
    name: 语法格式验证
    # runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 仓库获取
        uses: actions/checkout@v3
      - name: 安装python ${{ env.python-version }}
        env:
          python-version: 3.9
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - name: 安装flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 flake8-bandit
      - name: 执行flake8
        run: make lint-ci