name: python-lint

on:
  workflow_call:

runs:
  using: composite
  steps:
    - name: 安装flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 flake8-bandit
    - name: 执行flake8
      run: make lint-ci
