name: python-lint

on:
  workflow_call:

permissions:
  contents: read

runs:
  using: composite
  steps:
    - name: pip更新flake8
      shell: bash
      run: |
        pwd
        python -m pip install --upgrade pip
        python -m pip install flake8 flake8-bandit
    - name: 执行flake8
      shell: bash
      run: make lint-ci
