name: python-lint

on:
  workflow_call:

permissions:
  contents: read

runs:
  using: composite
  steps:
    - name: 测试效果
      shell: bash
      run: |
        echo ${{ github.ref }}
        echo ${{ github.repository }}
        echo ${{ github.path }}
    - name: 安装flake8
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 flake8-bandit
    - name: 执行flake8
      shell: bash
      run: make lint-ci
